### ISSUE TITLE
Mod doesnt show in bz

### ISSUE THREAD

**Issue by RobbedParrot77** [K07H/DecorationsMod#11]
I have Qmod4 sml version checker and this for bz
And it doesn't show up
![20211031_114014](https://user-images.githubusercontent.com/93475188/139583048-99c402d3-ad17-4bfa-a298-d28700de42c0.jpg)
![20211031_113853](https://user-images.githubusercontent.com/93475188/139583054-3345bfc2-b550-4e3f-9e0d-ae3cd3a5dde5.jpg)

**Comment by CosmicGlowsticks** [comment]
Because it's not for BZ. They're different games, it will only work in the original. There is a BZ port in progress though, I'm pretty sure.

**Comment by Xiarno** [comment]
> Because it's not for BZ. They're different games, it will only work in the original. There is a BZ port in progress though, I'm pretty sure.

Maybe it's in progress... but without any update, we can only guess.
I wish the author at least gave us an update on how the port is going at all.
