### ISSUE TITLE
Drifting back to last base after game reload

### ISSUE THREAD

**Issue by vrogojin** [K07H/DecorationsMod#15]
Issue occurs after you detach from a base with your cyclop, go away and restart the game. After the reload, the cyclop believes somehow that it os still docked, even though it may be more than 1000 m away from the base. If the player quits un-docked cyclop, he/she still hets teleported to the base. Meanwhile, the cyclop drifts slowly back to the base in order to match back the docking hose.

Any work-around here?

P.S.: the game will not quit after this glitch. Pushing 'Yes' button does nothing.

![16465900783511673291452683046305](https://user-images.githubusercontent.com/23746834/156936031-6e629522-244e-415e-9216-a1144f57e03f.jpg)

**Comment by K07H** [comment]
Fixed in latest version of the mod.
