### ISSUE TITLE
Can't make Decorations Fabricator

### ISSUE THREAD

**Issue by itsgreenbanana** [K07H/DecorationsMod#6]
Alright, so I don't know if I am just an idiot, but I cannot figure out how to make the fabricator. I think something is wrong with my installation, but not sure. My SML Tech Type Cache shows all of the mod's items, so I assume I am an idiot. I also can't spawn them with the console.

**Comment by K07H** [comment]
Hello itsgreenbanana,

Fabricators are located in the Habitat Builder tool menu.
Have you tried on a brand new game to see if this also happens?

You could verify that you have latest version of the game, latest version of QModManager and latest version SML Helper installed.

You can look inside your output log file and check if you can find the reason of the issue.
It is located here : %userprofile%\appdata\locallow\Unknown Worlds\Subnautica\Player.log

You could try to get some help in the "modding-support" channel of the Discord server.
Here : https://discord.gg/jKAFp8

Thank you.
