### ISSUE TITLE
Below Zero ?

### ISSUE THREAD

**Issue by Xiarno** [K07H/DecorationsMod#9]
Will there be a version for BZ ?

**Comment by K07H** [comment]
Yes there is already one that I made when BZ was still in preview release, but it needs an update now that the game has been officially released.

**Comment by Xiarno** [comment]
> Yes there is already one that I made when BZ was still in preview release, but it needs an update now that the game has been officially released.

Sick ! Can't wait !
I much prefer BZ so I can't wait !
